services:
  postgres:
    image: postgres:15-alpine
    container_name: ip_reversal_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mypass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d ip_reversal_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ip_reversal_app
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/ip_reversal_db
      - DEBUG=true
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app_network
    command: uvicorn src.api:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge