# Default values for ip-reversal-app
# This is a YAML-formatted file.

# Application configuration
app:
  name: "IP Reversal Service"
  version: "1.0.0"

# Image configuration
image:
  repository: ghcr.io/your-username/ip-reversal-app
  tag: "latest"
  pullPolicy: IfNotPresent

# Application replica count
replicaCount: 2

# Application configuration
config:
  debug: false
  host: "0.0.0.0"
  port: 8000

# Database configuration
database:
  # Use external database (recommended for production)
  external:
    enabled: true
    host: "your-postgres-host"
    port: 5432
    name: "ip_reversal_db"
    user: "user"
    password: "password"
    sslMode: "require"
  
  # Internal database (for development/testing)
  internal:
    enabled: false
    image:
      repository: postgres
      tag: "15-alpine"
    persistence:
      enabled: true
      size: 10Gi
      storageClass: ""

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
  annotations: {}

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: ip-reversal.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ip-reversal-tls
      hosts:
        - ip-reversal.yourdomain.com

# Resource limits and requests
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Health check configuration
healthCheck:
  livenessProbe:
    httpGet:
      path: /api/health
      port: 8000
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
  readinessProbe:
    httpGet:
      path: /api/health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 5
    timeoutSeconds: 3
    failureThreshold: 3

# Security configuration
security:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Pod security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Container security context
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Environment variables
env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: ip-reversal-secrets
        key: database-url
  - name: DEBUG
    value: "false"

# Secrets configuration
secrets:
  enabled: true
  databaseUrl: "postgresql://user:password@your-postgres-host:5432/ip_reversal_db"

# Service account
serviceAccount:
  create: true
  name: "ip-reversal-sa"
  annotations: {}

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Network policies
networkPolicy:
  enabled: false
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: 8000

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 10s
  podMonitor:
    enabled: false 