apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ip-reversal-app-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/ip-reversal-app.git
    targetRevision: HEAD
    path: helm-chart
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: image.tag
          value: latest
        - name: database.external.host
          value: your-postgres-staging-host
        - name: database.external.password
          value: your-postgres-staging-password
        - name: ingress.hosts[0].host
          value: staging.ip-reversal.yourdomain.com
        - name: replicaCount
          value: "1"
        - name: hpa.enabled
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5 